name       : obs-vkcapture
version    : 1.3.0
release    : 5
source     :
    - https://github.com/nowrep/obs-vkcapture/archive/refs/tags/v1.3.0.tar.gz : ec3366abdba6c74af8cd83a4ffadd45ce4dadaf66542233b05e7881af754fb83
license    : GPL-2.0-or-later
homepage   : https://github.com/nowrep/obs-vkcapture
component  : multimedia.video
summary    : OBS plugin for Vulkan/OpenGL game capture on Linux
description: |
    OBS plugin for Vulkan/OpenGL game capture on Linux
emul32     : yes
libsplit   : no
builddeps  :
    - pkgconfig(libobs)
    - pkgconfig32(opengl)
    - pkgconfig32(vulkan)
    - pkgconfig32(wayland-client)
    - vulkan-headers
setup      : |
    if [[ ! -z $EMUL32BUILD ]]; then
        %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib32 -DBUILD_PLUGIN=$OFF
    else
        %cmake_ninja
    fi
build      : |
    %ninja_build
install    : |
    %ninja_install
