name       : obs-vkcapture
version    : 1.3.2
release    : 6
source     :
    - https://github.com/nowrep/obs-vkcapture/archive/refs/tags/v1.3.2.tar.gz : f82cc781741b189f9d4199176d5098f8b68a6f9e9c3f9ef03435d7e2581ef79f
license    : GPL-2.0-or-later
homepage   : https://github.com/nowrep/obs-vkcapture
component  : multimedia.video
summary    : OBS plugin for Vulkan/OpenGL game capture on Linux
description: |
    OBS plugin for Vulkan/OpenGL game capture on Linux
emul32     : yes
libsplit   : no
builddeps  :
    - pkgconfig(libobs)
    - pkgconfig32(opengl)
    - pkgconfig32(vulkan)
    - pkgconfig32(wayland-client)
    - vulkan-headers
setup      : |
    if [[ ! -z $EMUL32BUILD ]]; then
        %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib32 -DBUILD_PLUGIN=$OFF
    else
        %cmake_ninja
    fi
build      : |
    %ninja_build
install    : |
    %ninja_install
